# Generated by Django 3.2 on 2023-07-29 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('elevator_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_floor', models.PositiveIntegerField(default=1)),
                ('direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('STOPPED', 'Stopped')], default='STOPPED', max_length=10)),
                ('is_working', models.BooleanField(default=True)),
                ('is_door_open', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField()),
                ('direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], max_length=10)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='elevators.elevator')),
            ],
        ),
    ]
